#Variables
@baseUrl = http://localhost:3333

# Get health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
POST {{baseUrl}}/rooms
# @name createRoom
Content-Type: application/json

{
  "name": "Uma sala bonita",
  "description": "Uma descrição bonita"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions